#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Reima Kumamoto
# SPDX-Licence-Identifier: GPL-3.0

import sys

ans = 0
count = 0

for line in sys.stdin:
    try:
        num = int(line)
        ans += num
        count += 1
    except:
        num = float(line)
        ans += num
        count += 1
              

if count > 0:
    average = ans / count
    print(f"{ans}, {average}")


